name: Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          target/
        key: ${{ runner.os }}-cargoc-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargoc-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargoc-
          ${{ runner.os }}-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-
    - name: Install cargo-c
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-c
    - name: Run cargo-c tests
      uses: actions-rs/cargo@v1
      with:
        command: ctest
        args: --release
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: cinstall
        args: --release --prefix=/usr --destdir=./build
    - name: Compress
      run: tar cvzf biscuit_c-${{github.ref_name}}-x86_64.tar.gz -C build/ .
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: biscuit_c-${{github.ref_name}}-x86_64.tar.gz
