name: Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install cargo-c
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-c
    - name: Run cargo-c tests
      uses: actions-rs/cargo@v1
      with:
        command: ctest --release
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: cinstall ---release -prefix=/usr --destdir=./build
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: biscuit_c-${{github.ref_name}}-x86_64
        path: build/
